Rust-GPU/rust-gpu

CHANGELOG.md
crates/spirv-builder/src/lib.rs

Adds fields for default-features and features to SpirvBuilder [and] pipes those fields through to the cargo command that builds the shader crate.
[Original PR in embark's repo](https://github.com/EmbarkStudios/rust-gpu/pull/1124)

Shader crate cargo features

---

README.md

Wanted to get something down so people can discover it. Feel free to suggest wording.

Add GitHub discussions to README

---

examples/runners/wgpu/src/compute.rs

Gracefully handle absence of adapter timestamping support in wpgu-runner.
Check for adapter support at runtime and only collect timing data if it does.

Support-dependent timestamping in wpgu-runner compute example 

---

Cargo.lock
crates/rustc_codegen_spirv/Cargo.toml
crates/rustc_codegen_spirv/src/codegen_cx/mod.rs
crates/rustc_codegen_spirv/src/linker/mod.rs
crates/rustc_codegen_spirv/src/linker/spirt_passes/controlflow.rs
crates/rustc_codegen_spirv/src/linker/spirt_passes/debuginfo.rs
crates/rustc_codegen_spirv/src/linker/spirt_passes/diagnostics.rs
crates/rustc_codegen_spirv/src/linker/spirt_passes/mod.rs
crates/rustc_codegen_spirv/src/linker/spirt_passes/reduce.rs
docs/src/codegen-args.md
tests/ui/dis/entry-pass-mode-cast-array.stderr
tests/ui/dis/index_user_dst.stderr
tests/ui/dis/issue-731.stderr
tests/ui/dis/panic_builtin_bounds_check.stderr
tests/ui/dis/panic_sequential_many.rs
tests/ui/dis/panic_sequential_many.stderr
tests/ui/lang/core/unwrap_or.stderr

This PR improves structurization of panics and other functions that exit the invocation, like `OpKill` (`discard;` in glsl) in fragment shaders. This should hopefully reduce the amount of structurization errors in the resulting spv.
Mainly developed by @eddyb with some test fixes by @LegNeato

Panic structurization improvements

---

crates/spirv-builder/src/lib.rs

This adds an optional explicit path to `spirv-builder` that is used to locate the `rustc_codegen_spirv` dynamic lib.

feat: spirv-builder takes an optional path to locate rustc_codegen_spirv

---

.github/workflows/ci.yaml

See also:
- https://github.com/EmbarkStudios/spirt/pull/20
- https://github.com/Rust-GPU/spirt/commit/af5445d366c932788d1b9fec36203f4371339d02
- [relevant GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#configuring-continuous-integration-ci-workflows-for-merge-queues)

ci: enable GitHub Actions for merge queues.

---

crates/spirv-std/src/arch/subgroup.rs
tests/ui/arch/subgroup/subgroup_ballot.stderr
tests/ui/arch/subgroup/subgroup_ballot_bit_count.rs
tests/ui/arch/subgroup/subgroup_ballot_bit_count.stderr
tests/ui/arch/subgroup/subgroup_broadcast_first.stderr
tests/ui/arch/subgroup/subgroup_elect.stderr
tests/ui/arch/subgroup/subgroup_i_add_clustered.rs
tests/ui/arch/subgroup/subgroup_i_add_clustered.stderr
tests/ui/arch/subgroup/subgroup_i_add_exclusive_scan.rs
tests/ui/arch/subgroup/subgroup_i_add_exclusive_scan.stderr
tests/ui/arch/subgroup/subgroup_i_add_inclusive_scan.rs
tests/ui/arch/subgroup/subgroup_i_add_inclusive_scan.stderr
tests/ui/arch/subgroup/subgroup_i_add_reduce.rs
tests/ui/arch/subgroup/subgroup_i_add_reduce.stderr

I wasn't a big fan of how I exposed subgroup ops that require a value from the `GroupOperation` enum. This PR changes all of those functions to be much more like glsl exposes them. 
These operations:
```rust
spirv_std::arch::subgroup_i_add::<{ GroupOperation::Reduce as u32 }, _>(value)
spirv_std::arch::subgroup_i_add::<{ GroupOperation::InclusiveScan as u32 }, _>(value)
spirv_std::arch::subgroup_i_add::<{ GroupOperation::ExclusiveScan as u32 }, _>(value)
spirv_std::arch::subgroup_i_add_clustered::<8, _>(value)
```
Got changed to this:
```rust
spirv_std::arch::subgroup_i_add(value)
spirv_std::arch::subgroup_inclusive_i_add(value)
spirv_std::arch::subgroup_exclusive_i_add(value)
spirv_std::arch::subgroup_clustered_i_add::<8, _>(value)
```
The new function names are *almost* exactly the same …

make subgroup ops match glsl more closely

---

.github/workflows/ci.yaml

Hey all! First time contributor (to any open-source project!!!!)
I saw issue #40 and decided to try and see if I could get an action added. I've pretty much just added another example (also runs example-runner-wgpu-builder) but left out --release. 
I was a bit unsure about the OUT_DIR environment variable, and if it was necessary (not even sure why it's there for the existing example run?) but I assumed it should remain for consistency. 
On top of that, I was going to look at adding a dev profile build for android, but it seems that cargo-apk is outdated, and the maintainers of the project recommend [xbuild](https://github.com/rust-mobile/xbuild), though I am unsure if profiles (--release) are forwarded to cargo or not. Will have to play around with it.
I'm also unsure if I'm able to run …

Added non release (dev) shader build

---

crates/rustc_codegen_spirv/src/linker/mod.rs
crates/rustc_codegen_spirv/src/linker/spirt_passes/diagnostics.rs

Originally opened at:
- https://github.com/EmbarkStudios/rust-gpu/pull/1088
I had kept putting off landing this because ideally there would be fractal panic catching and automatic retries, but the existing improvements (wrt debugging e.g. panics originating in SPIR-T passes) are worth landing already.

linker: also dump SPIR-T on panic, not just during successful compilation.

---

crates/spirv-builder/src/lib.rs

This adds an optional field to `SpirvBuilder` that will set the "target specification" file. This will enable [cargo-gpu](https://github.com/rust-gpu/cargo-gpu) to point to these files, which can be stored in its cache directory.
* https://github.com/Rust-GPU/cargo-gpu/issues/10
* https://github.com/Rust-GPU/rust-gpu/issues/22
* https://github.com/EmbarkStudios/rust-gpu/issues/1137

feat: spirv-builder takes optional path to target spec JSON file

---

Cargo.lock
crates/rustc_codegen_spirv/Cargo.toml

Updating indexmap because 1.6 depends on a ahash version that makes use of the `stdsimd` feature which no longer exists and was causing compile errors.

Update `indexmap` from 1.6 to 2.6

---

docs/src/writing-shader-crates.md

Resolves #157 
Improves the .cargo/config section because the instruction weren't quite correct.

Update .cargo/config section of writing-shader-crates.md

---

Cargo.lock
crates/rustc_codegen_spirv/Cargo.toml
crates/spirv-std/macros/Cargo.toml
crates/spirv-std/macros/src/lib.rs
deny.toml

This was the last dependency in my project that still uses syn 1.0 :D
Note that within the repo there remains one usage of syn 1.0 on *some* targets (I assume windows only):
```
$ cargo tree -i syn@1 --target all
syn v1.0.109
├── com_macros v0.6.0 (proc-macro)
│   └── com v0.6.0
│       └── hassle-rs v0.11.0
│           └── wgpu-hal v22.0.0
│               ├── wgpu v22.1.0
│               │   └── example-runner-wgpu v0.0.0 (/rust-gpu/examples/runners/wgpu)
│               └── wgpu-core v22.1.0
│                   └── wgpu v22.1.0 (*)
└── com_macros_support v0.6.0
└── com_macros v0.6.0 (proc-macro) (*)
```

update to syn 2.0

---

crates/rustc_codegen_spirv/src/builder/intrinsics.rs
tests/ui/lang/core/intrinsics/bswap.rs

Fixes https://github.com/Rust-GPU/rust-gpu/issues/169

Support signed integers for `bswap` intrinsic

---

crates/spirv-std/src/byte_addressable_buffer.rs

* fix oob calculation thinking all buffers are only `len / 4` long
* fix debug printf mispile, segfaulting debug printf validation layer
android ci is broken right now, see https://github.com/Rust-GPU/rust-gpu/pull/180

ByteAddressableBuffer fixes

---

examples/runners/wgpu/src/graphics.rs

This unbreaks Wayland (I had been using `WAYLAND_DISPLAY= cargo run ...` for ages instead of investigating it, turns out to have been something very silly).
This is what the bug looked like:
```
wp_linux_drm_syncobj_manager_v1#63: error 0: surface already exists
thread 'main' panicked at /home/eddy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-22.1.0/src/device/global.rs:1930:25:
internal error: entered unreachable code: Fallback system failed to choose present mode. This is a bug. Mode: AutoVsync, Options: []
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I kept thinking maybe this is a Wayland protocol mismatch or something, but no, Mesa (the opensource GPU driver stack for Linux) has a bug:
- [Vulkan/WSI/Wayland: `wsi_wl_surface_init` …

examples/runners/wgpu: avoid holding onto to multiple surfaces at the same time.

---

Cargo.lock
deny.toml
examples/runners/ash/Cargo.toml
examples/runners/ash/src/main.rs
examples/runners/wgpu/Cargo.toml
examples/runners/wgpu/src/compute.rs
examples/runners/wgpu/src/graphics.rs

Relevant release notes:
- https://github.com/rust-windowing/winit/releases/tag/v0.30.0
- this PR still uses the deprecated APIs (maybe should migrate to the new ones?)
- https://github.com/gfx-rs/wgpu/releases/tag/v23.0.0
- very few changed needed, more of a bug fix + features release, than breaking

examples/runners/{ash,wgpu}: update `winit` to `0.30`, `wgpu` to `23`.

---

examples/runners/ash/src/main.rs

Hello,
Building the Vulkan runner failed on my ARM 64 Ubuntu virtual machine with the following error:
```
error[E0277]: a value of type `Vec<*const i8>` cannot be built from an iterator over elements of type `*const u8`
--> examples/runners/ash/src/main.rs:319:18
|
319  |                 .collect();
|                  ^^^^^^^ value of type `Vec<*const i8>` cannot be built from `std::iter::Iterator<Item=*const u8>`
|
= help: the trait `FromIterator<*const u8>` is not implemented for `Vec<*const i8>`
but trait `FromIterator<*const i8>` is implemented for it
= help: for that trait implementation, expected `i8`, found `u8`
note: the method call chain might not have had the expected associated types
--> examples/runners/ash/src/main.rs:318:18
|
311  |               let layer_names = if …
```

Fix C string char type to use portable type c_char.

---

crates/spirv-builder/src/lib.rs

Had this lying around intermixed with `-Zscript` experiments I never completed, and we keep running into situations where this simple addition would be useful.

spirv-builder: add `RUSTGPU_CARGOFLAGS`, as a Cargo counterpart to `RUSTGPU_RUSTFLAGS` (for `rustc`).

---

CHANGELOG.md

These were not included with their respective PRs. I removed all the different toolchain updates as it can be confusing. I think we just need to keep the latest one. Finally, I made the tense consistent (used past tense so it reads well with the beginning PR#) and spacing / bullets consistent.

Add recent changes to CHANGELOG

---

crates/spirv-builder/src/lib.rs

This was my issue and it was unclear the cause. I am not sure if this is the only case where this error shows up, hence the wording. Open to better wording if you have it.

Add a message to suggest checking crate-type

---

crates/rustc_codegen_spirv/src/builder/intrinsics.rs
crates/rustc_codegen_spirv/src/builder/libm_intrinsics.rs
crates/rustc_codegen_spirv/src/builder/mod.rs
crates/rustc_codegen_spirv/src/codegen_cx/constant.rs

**best reviewed commit by commit**
I see this quite commonly:
```rust
let undef = self.undef(ret_ty);
self.zombie(undef.def(self), "memcmp not implemented");
undef
```
And I replaced it with this:
```rust
self.undef_zombie(ret_ty, "memcmp not implemented")
```
Among other smaller cleanups

Undef zombie and some other code cleanups

---

crates/spirv-builder/src/lib.rs

If you have two shader crates, one has to wait for the other to finish compiling before it can compile. That's a good thing, as you don't have to recompile any dependencies twice. 
But if you have two shader crates **with differing capabilities or features**, they are forced to do a clean rebuild every time, **adding 30s each build, even if nothing changed**. Explicitly specifying a target dir enables me to specify a separate build dir for each shader crate and work around this issue. 
I do think a better policy wrt. capabilities and features will be needed in the future, but this will do for now.

add `SpirvBuilder::target_dir_path` to set the target dir explicitly

---

crates/rustc_codegen_spirv/src/builder/builder_methods.rs

I don't really know when this applies, just saw it while reading the code.

Fix typo swapping logical operations on bools

---

crates/spirv-std/macros/src/lib.rs
crates/spirv-std/src/arch/derivative.rs
crates/spirv-std/src/sealed.rs
tests/ui/arch/derivative.rs
tests/ui/arch/derivative.stderr
tests/ui/arch/derivative_control.rs
tests/ui/arch/derivative_control.stderr

Adds a new `trait Derivative` that is implemented for `f32`, `Vec2`, `Vec3`, `Vec3A` and `Vec4`. Disallows f64 to be derived, spec expects f32 only. Renamed derivatives from `ddx()` to `dfdx()` to better match glsl's `dFdx()`.
Spec section: https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_derivative_instructions

refactor derivatives

---

.github/workflows/ci.yaml

> This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101

ci: update ubuntu runners to 24.04

---

crates/rustc_codegen_spirv/src/spirv_type.rs
tests/ui/dis/asm_op_decorate.stderr

Stop decorating `RuntimeArrays` of unsized types with `ArrayStride`. Fixes the `spirv-val` rule:
```
Array containing a Block or BufferBlock must not be decorated with ArrayStride
```
This already works correctly when using `qptrs`.

Only decorate physically sized types with ArrayStride

---

Cargo.lock
Cargo.toml
crates/spirv-std/Cargo.toml

closes https://github.com/Rust-GPU/rust-gpu/pull/243

force `libm <=0.2.11`, as `0.2.12` has breaking changes

---

.cargo/config.toml
docs/src/building-rust-gpu.md

Windows by default will use the `msvc` linker, which maxes out on 2^16-1 symbols, which the ash and wgpu examples in debug mode easily exceed.
Solution: rust-lld.exe, which _should_ be available already as it's in the llvm-tools that the `rust-toolchain.toml` will be ensuring is installed anyway.

Fix windows builds

---

examples/runners/wgpu/src/lib.rs

Updates the help-menu on the `wgpu-runner` to avoid others making the mistake I made [here](https://github.com/Rust-GPU/rust-gpu/issues/253).
Before:
```sh
Usage: example-runner-wgpu.exe [OPTIONS]
Options:
-s, --shader <SHADER>       [default: Sky]
--force-spirv-passthru
-h, --help                  Print help
```
After:
```sh
Usage: example-runner-wgpu.exe [OPTIONS]
Options:
-s, --shader <SHADER>       which shader to run [default: sky] [possible values: simplest, sky, compute, mouse]
--force-spirv-passthru
-h, --help                  Print help
```
closes https://github.com/Rust-GPU/rust-gpu/issues/253

fix: buff the help menu for the wgpu-runner

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
crates/rustc_codegen_spirv-target-specs/src/include_str.rs
crates/rustc_codegen_spirv-target-specs/target-specs/spirv-unknown-spv1.6.json
crates/rustc_codegen_spirv-target-specs/target-specs/spirv-unknown-vulkan1.3.json
crates/rustc_codegen_spirv-target-specs/target-specs/spirv-unknown-vulkan1.4.json
crates/rustc_codegen_spirv/src/target.rs
crates/spirv-builder/src/lib.rs
docs/src/platform-support.md
tests/compiletests/ui/dis/asm_op_decorate.rs
tests/compiletests/ui/dis/non-writable-storage_buffer.rs
tests/compiletests/ui/image/gather.rs
tests/compiletests/ui/image/query/rect_image_query_size.rs
tests/compiletests/ui/image/query/sampled_image_rect_query_size_lod_err.rs
tests/compiletests/ui/image/sample_depth_reference/sample_gradient.rs
tests/compiletests/ui/image/sample_depth_reference/sample_lod.rs

~~I thought it'll be easy going, but it seems like spv1.6 introduced some new validation we're now failing.~~ Nope, just some tests excluded for vulkan that need their target list extended.

add targets `vulkan1.3`, `vulkan1.4` and `spv1.6`

---

crates/rustc_codegen_spirv/src/builder/builder_methods.rs
crates/rustc_codegen_spirv/src/codegen_cx/declare.rs
crates/rustc_codegen_spirv/src/codegen_cx/mod.rs
crates/rustc_codegen_spirv/src/linker/mod.rs
crates/rustc_codegen_spirv/src/linker/simple_passes.rs
crates/rustc_codegen_spirv/src/spirv_type.rs
tests/compiletests/ui/dis/asm_op_decorate.stderr
tests/compiletests/ui/dis/const-float-cast-optimized.rs
tests/compiletests/ui/dis/const-float-cast-optimized.stderr
tests/compiletests/ui/dis/const-float-cast.rs
tests/compiletests/ui/dis/const-float-cast.stderr
tests/compiletests/ui/dis/const-from-cast.rs
tests/compiletests/ui/dis/const-from-cast.stderr
tests/compiletests/ui/dis/const-int-cast.rs
tests/compiletests/ui/dis/const-int-cast.stderr
tests/compiletests/ui/dis/const-narrowing-cast.rs
tests/compiletests/ui/dis/const-narrowing-cast.stderr
tests/compiletests/ui/dis/custom_entry_point.stderr
tests/compiletests/ui/dis/generic-fn-op-name.stderr
tests/compiletests/ui/dis/issue-723-output.stderr
tests/compiletests/ui/dis/non-writable-storage_buffer.stderr
tests/compiletests/ui/dis/panic_builtin_bounds_check.stderr
tests/compiletests/ui/dis/panic_sequential_many.stderr
tests/compiletests/ui/dis/spec_constant-attr.stderr
tests/compiletests/ui/lang/consts/u32-from-u64-fail.rs
tests/compiletests/ui/lang/consts/u32-from-u64-fail.stderr
tests/compiletests/ui/lang/consts/u8-const-cast-no-capability.rs
tests/compiletests/ui/lang/consts/u8-const-cast.rs

Add constant folding for widening casts (u8->u32, f32->f64) to avoid creating intermediate types. Remove capability checks during type creation and add bidirectional validation in linker to remove unused type capabilities.
Fixes #300

Optimize constant casts to avoid unnecessary capabilities

---

crates/spirv-std/src/arch.rs
tests/compiletests/src/main.rs
tests/compiletests/ui/dis/asm_op_decorate.stderr
tests/compiletests/ui/dis/const-float-cast-optimized.stderr
tests/compiletests/ui/dis/const-float-cast.stderr
tests/compiletests/ui/dis/const-from-cast.stderr
tests/compiletests/ui/dis/const-int-cast.stderr
tests/compiletests/ui/dis/const-narrowing-cast.stderr
tests/compiletests/ui/dis/custom_entry_point.stderr
tests/compiletests/ui/dis/generic-fn-op-name.stderr
tests/compiletests/ui/dis/issue-723-output.stderr
tests/compiletests/ui/dis/non-writable-storage_buffer.stderr
tests/compiletests/ui/dis/panic_builtin_bounds_check.stderr
tests/compiletests/ui/dis/panic_sequential_many.stderr
tests/compiletests/ui/dis/spec_constant-attr.rs
tests/compiletests/ui/dis/spec_constant-attr.stderr

split out from https://github.com/Rust-GPU/rust-gpu/pull/280 to get it merged sooner
Currently, the `arch::read_clock_khr` function is hidden behind it's `target_feature` gates `ShaderClockKHR` and `ext:SPV_KHR_shader_clock`, unlike every other intrinsic we have. Usually, the functions are always available and `spirv-val` just fails if you use a feature without enabling it. This PR removes the feature gate.
It also removes that extension and capability from the ones enabled by default in compiletest, as naga does not support it, to unblock https://github.com/Rust-GPU/rust-gpu/pull/280

Make `read_clock_khr` always available

---

Cargo.lock
deny.toml
examples/runners/wgpu/Cargo.toml
examples/runners/wgpu/src/compute.rs
examples/runners/wgpu/src/graphics.rs
examples/runners/wgpu/src/lib.rs
tests/difftests/lib/Cargo.toml
tests/difftests/lib/src/config.rs
tests/difftests/lib/src/scaffold/compute/wgpu.rs
tests/difftests/tests/Cargo.lock

split out from https://github.com/Rust-GPU/rust-gpu/pull/280 to get it merged sooner

Upgrade wgpu 23 -> 25

---

tests/difftests/bin/src/main.rs

These all now work. Previously, the path ones did not work:
- cargo difftest -- difftests::arch::workgroup_memory (original format)
- cargo difftest -- arch/workgroup_memory (path-like format)
- cargo difftest -- arch (directory filter)

Support more test names in difftest

---

crates/spirv-std/src/arch/subgroup.rs
tests/compiletests/ui/arch/subgroup/subgroup_ballot.stderr
tests/compiletests/ui/arch/subgroup/subgroup_ballot_bit_count.stderr
tests/compiletests/ui/arch/subgroup/subgroup_broadcast_first.stderr
tests/compiletests/ui/arch/subgroup/subgroup_cluster_size_0_fail.rs
tests/compiletests/ui/arch/subgroup/subgroup_cluster_size_0_fail.stderr
tests/compiletests/ui/arch/subgroup/subgroup_cluster_size_non_power_of_two_fail.rs
tests/compiletests/ui/arch/subgroup/subgroup_cluster_size_non_power_of_two_fail.stderr
tests/compiletests/ui/arch/subgroup/subgroup_elect.stderr
tests/compiletests/ui/arch/subgroup/subgroup_i_add_clustered.stderr
tests/compiletests/ui/arch/subgroup/subgroup_i_add_exclusive_scan.stderr
tests/compiletests/ui/arch/subgroup/subgroup_i_add_inclusive_scan.stderr
tests/compiletests/ui/arch/subgroup/subgroup_i_add_reduce.stderr

Fixes #305. Here is what I decided to allow, and the justification for each.
|Change|Justification|
|-|-|
|OpControlBarrier|Spec says: "When Execution is Workgroup or larger, behavior is undefined [...]" Execution is Subgroup.|
|OpMemoryBarrier|Memory barriers are always defined.|
|OpGroupNonUniformElect|Subgroup election is always defined.|
|OpGroupNonUniformAll|Subgroup predicate evaluation is always defined.|
|OpGroupNonUniformAny|Subgroup predicate evaluation is always defined.|
|OpGroupNonUniformAllEqual|Subgroup predicate evaluation is always defined.|
|OpGroupNonUniformBroadcastFirst|Subgroup broadcast first is always defined.|
|OpGroupNonUniformBallot|Subgroup ballot is always defined.|
|OpGroupNonUniformBallotBitExtract|Subgroup bit extract is safe. The result of subgroup bit …

Remove unsafe from unconditionally safe subgroup ops

---

tests/compiletests/src/main.rs

Without this change it accidentally used
tests/target/compiletest-{deps,results} instead of the workspace target dir
@eddyb pointed this out.

Update compiletest target path

---

crates/rustc_codegen_spirv/src/builder/builder_methods.rs
crates/rustc_codegen_spirv/src/codegen_cx/declare.rs

*(Each commit should be reviewed separately)*
---
The main "externally" visible change is the "force warnings" one - thought it's still mostly just for us.
Due to Cargo using `--cap-lints`, you normally can't see warnings in non-local dependencies - and that includes the standard library when using `-Zbuild-std` (like we do).
So every time the "`format_args!` decompiler" would fail (e.g. while working on a `rustup`, before updating it) for a `panic!` in e.g. `core`, it would silently cause issues downstream (while making it harder to diagnose)
After this PR, it will always warn in the crate responsible (though hopefully never, for Rust-GPU users).
---
I've had this "force warnings" change around for a while, but never submitted it because there were always a few warnings from `core` - …

`format_args!` "decompiler": forced warnings and `fmt::Arguments::new_v1_formatted` "support".

---

.github/workflows/lint.sh
tests/compiletests/src/main.rs
tests/difftests/bin/src/main.rs
tests/difftests/bin/src/runner.rs
tests/difftests/lib/src/lib.rs

clippy doesn't run on eg. compiletest and difftest and there's some code it's complaining about

ci: enable clippy for more crates

---

.github/workflows/ci.yaml
.github/workflows/lint.sh
Cargo.lock
Cargo.toml

> Hmpf, unfortunate that we can't pass the features somehow, to a single `cargo clippy --workspace` invocation.
> 
> Alternatively, it might be nice to not have SPIRV-Tools' C++ code be compiled by `spirv-tools-rs` when built for `cargo check`/`cargo clippy`, but I don't recall if that's even feasible to do.
https://github.com/Rust-GPU/rust-gpu/pull/329#pullrequestreview-3009595291
Well, now we can :D
This also speeds up our lint CI from 7m to 6m, likely from better multi-core utilization due to checking more crates in parallel

ci: simplify clippy

---

crates/rustc_codegen_spirv/src/symbols.rs

Vulkan extension: https://registry.khronos.org/vulkan/specs/latest/man/html/HitTriangleVertexPositionsKHR.html
SPIRV extension: https://github.khronos.org/SPIRV-Registry/extensions/KHR/SPV_KHR_ray_tracing_position_fetch.html
Note that this PR only adds the RayTracing[Pipeline] part, not the RayQuery part.

Add HitTriangleVertexPositionsKHR built-in for ray tracing pipelines

---

crates/rustc_codegen_spirv/src/spirv_type_constraints.rs
crates/spirv-std/src/ray_tracing.rs
tests/compiletests/ui/arch/ray_query_get_intersection_triangle_vertex_positions.rs

followup from https://github.com/Rust-GPU/rust-gpu/pull/339 adding it for ray_tracing pipelines
Vulkan extension: https://registry.khronos.org/vulkan/specs/latest/man/html/HitTriangleVertexPositionsKHR.html
SPIRV extension: https://github.khronos.org/SPIRV-Registry/extensions/KHR/SPV_KHR_ray_tracing_position_fetch.html

Add `RayQuery::get_intersection_triangle_vertex_positions()` extension

---

crates/rustc_codegen_spirv/src/builder/builder_methods.rs
crates/rustc_codegen_spirv/src/builder/ext_inst.rs
crates/rustc_codegen_spirv/src/builder/intrinsics.rs
crates/rustc_codegen_spirv/src/builder/mod.rs
crates/rustc_codegen_spirv/src/builder/spirv_asm.rs
crates/rustc_codegen_spirv/src/builder_spirv.rs
crates/rustc_codegen_spirv/src/codegen_cx/declare.rs
crates/rustc_codegen_spirv/src/codegen_cx/entry.rs
crates/rustc_codegen_spirv/src/codegen_cx/mod.rs

As may be obvious from the first commit, I was hoping to remove the `RefCell` around the `rspirv::dr::Builder`.
<sub>(it's still possible, but it would require keeping global and function builders separate, and using different ID ranges, and I almost jerry-rigged some contraption using `spirt::{Context,Type,Const}` but it'd be too much work to port everything over, not to mention new exciting failure modes)</sub>
---
Instead, I ended up fixing a long-standing issue with how we expose SPIR-V functions and blocks to `rustc_codegen_ssa` - which is mostly straight-forward, as it already has associated types for `Function` and `BasicBlock`, we were just using raw SPIR-V IDs (or `SpirvValue`, in the case of `Function`) for no good reason.
After this PR, we're always tracking the …

Customize `Function` and `BasicBlock` to carry both a SPIR-V ID and an index, for O(1) access.

---

Cargo.toml
crates/rustc_codegen_spirv/src/builder/builder_methods.rs
crates/rustc_codegen_spirv/src/builder/libm_intrinsics.rs
tests/compiletests/ui/dis/entry-pass-mode-cast-array.stderr
tests/compiletests/ui/dis/issue-731.stderr
tests/compiletests/ui/lang/u32/const_fold_div.rs
tests/difftests/tests/Cargo.lock
tests/difftests/tests/Cargo.toml
tests/difftests/tests/lang/core/ops/const_fold_int/const-expr-cpu/Cargo.toml
tests/difftests/tests/lang/core/ops/const_fold_int/const-expr-cpu/src/main.rs
tests/difftests/tests/lang/core/ops/const_fold_int/const-expr-shader/Cargo.toml
tests/difftests/tests/lang/core/ops/const_fold_int/const-expr-shader/src/lib.rs
tests/difftests/tests/lang/core/ops/const_fold_int/const-expr-shader/src/main.rs
tests/difftests/tests/lang/core/ops/const_fold_int/const-fold-cpu/Cargo.toml
tests/difftests/tests/lang/core/ops/const_fold_int/const-fold-cpu/src/cpu_driver.rs
tests/difftests/tests/lang/core/ops/const_fold_int/const-fold-cpu/src/lib.rs
tests/difftests/tests/lang/core/ops/const_fold_int/const-fold-cpu/src/main.rs
tests/difftests/tests/lang/core/ops/const_fold_int/const-fold-cpu/src/shader.rs
tests/difftests/tests/lang/core/ops/const_fold_int/const-fold-cpu/src/shader_driver.rs
tests/difftests/tests/lang/core/ops/const_fold_int/const-fold-shader/Cargo.toml
tests/difftests/tests/lang/core/ops/const_fold_int/const-fold-shader/src/lib.rs
tests/difftests/tests/lang/core/ops/const_fold_int/const-fold-shader/src/main.rs
tests/difftests/tests/lang/core/ops/const_fold_int/dynamic-values-cpu/Cargo.toml
tests/difftests/tests/lang/core/ops/const_fold_int/dynamic-values-cpu/src/main.rs
tests/difftests/tests/lang/core/ops/const_fold_int/dynamic-values-shader/Cargo.toml
tests/difftests/tests/lang/core/ops/const_fold_int/dynamic-values-shader/src/lib.rs
tests/difftests/tests/lang/core/ops/const_fold_int/dynamic-values-shader/src/main.rs

see https://github.com/Rust-GPU/rust-gpu/issues/300
const folding used to only support:
* basic int: add, mul
* casting from https://github.com/Rust-GPU/rust-gpu/pull/302
This PR adds const folding for:
* basic int: sub, div, rem, shr, lshl, ashl, neg, not (+ unchecked variants)
* basic bool: and, or, xor, not
* comparison for int and bool (`icmp`)
* select with const condition
Should probably add some diff tests

 better const folding for int and bool 

---

crates/rustc_codegen_spirv/src/codegen_cx/mod.rs
crates/rustc_codegen_spirv/src/lib.rs
crates/rustc_codegen_spirv/src/link.rs
crates/rustc_codegen_spirv/src/linker/mod.rs
crates/rustc_codegen_spirv/src/linker/test.rs
crates/rustc_codegen_spirv/src/linker/zombies.rs
docs/src/codegen-args.md
docs/src/tracing.md

The DCE ("dead code elimination", i.e. removing definitions not reachable from e.g. shader entry-points) pass was, for one reason or another, toggleable, and supposedly shaders should've still compiled without it.
However, the way this was achieved was by ignoring anything that DCE would've removed, in the "zombie" (deferred error) reporting pass, and removing the subset that also had "zombie" decorations.
Additionally, I believe that the concept of "optional DCE" has been outdated for a while, because of:
- *non-enumerable* SPIR-T interned (`Type`, `Const`) / module-scoped (`GlobalVar`, `Func`) handles
- that is, you can't even observe a `FooDef` without finding a `Foo` handle elsewhere
- everything has to be reached from `spirt::Module` exports (linker ones + shader entry-points)
(the …

Make DCE mandatory and run it much earlier (even per-crate, shrinking `.rlib`s).

---

crates/spirv-builder/src/lib.rs
examples/runners/wgpu/src/lib.rs

I noticed a few changes in the Vulkan Validation Layer documentation and ended up with these items:
- `multimodule` recommendation is no longer necessary (since Vulkan SDK 1.3.275.0):
- issue: https://github.com/KhronosGroup/SPIRV-Tools/issues/4892
- PR: https://github.com/KhronosGroup/SPIRV-Tools/pull/5495
- `DEBUG_PRINTF_TO_STDOUT=1` is now `VK_LAYER_PRINTF_TO_STDOUT=1` (since Vulkan SDK 1.3.283.0)
- old env var still works (just deprecated), but the new one fits in better
- PR: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7781
- `VK_KHR_shader_non_semantic_info` isn't required anymore (since Vulkan SDK 1.4.313.0)
- we should stop mentioning it, but it's recent and I left it in just in case
- issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9716
- …

Update `ShaderPanicStrategy::DebugPrintfThenExit` documentation for Vulkan SDK changes.

---

crates/rustc_codegen_spirv/src/linker/mod.rs
crates/rustc_codegen_spirv/src/linker/spirt_passes/mod.rs

While SPIR-T passes should, in principle, never panic, it can still happen (esp. with WIP code, where e.g. `assert!`s or `todo!()`s might be overrepresented etc.), and before this PR, the partially modified SPIR-T module would be completely lost in the `--dump-spirt-passes` output.
And because incomplete SPIR-T mutation could result in extremely malformed modules, this PR also wraps the SPIR-T pretty-printing in `std::panic::catch_unwind`, removing one pass' "after" state, at a time, from the pretty-printed versions, while it still panics, and showing an extra warning (with all the pass names that couldn't be printed) if that was necessary at all.
Also, there's a minor ergonomic fix in that `after_pass` doesn't need to also be passed the same string as `before_pass` (since …

Try dumping, when a SPIR-T pass panics, its in-progress `spirt::Module` state.

---

Cargo.toml
crates/rustc_codegen_spirv/src/codegen_cx/declare.rs

Resolves #242 in another way by allowing to update `libm` dependency
I think that backend tried to replace all the public functions usages inside of `libm` itself, which caused issue #242 in the first place.
Without suggested changes, compilation fails with ICE similar to this one:
```
error: internal compiler error: compiler\rustc_middle\src\ty\mod.rs:1631:13: item_name: no name for DefPath { data: [DisambiguatedDefPathData { data: TypeNs("math"), disambiguator: 0 }, DisambiguatedDefPathData { data: TypeNs("generic"), disambiguator: 0 }, DisambiguatedDefPathData { data: TypeNs("rint"), disambiguator: 0 }, DisambiguatedDefPathData { data: ValueNs("rint_round"), disambiguator: 0 }, DisambiguatedDefPathData { data: Closure, disambiguator: 0 }], krate: crate0 }
```
Note that local `DefId` …

Fix `libm` intrinsics for versions newer than `0.2.11`

---

crates/spirv-std/src/image.rs
tests/compiletests/ui/image/fetch_with_level.rs
tests/compiletests/ui/image/fetch_with_lod.rs
tests/compiletests/ui/image/gather_err.stderr
tests/compiletests/ui/image/query/query_levels_err.stderr
tests/compiletests/ui/image/query/query_lod_err.stderr
tests/compiletests/ui/image/query/query_size_err.stderr
tests/compiletests/ui/image/query/query_size_lod_err.stderr
tests/compiletests/ui/image/query/sampled_image_rect_query_size_lod_err.stderr

Fixes #360
I used the terminology `level` since that's what WGSL used, but it would also make sense to use `lod` since that's what SPIR-V and GLSL's `texelFetch` use.

Add Image::fetch_with_lod

---

Cargo.lock
Cargo.toml
tests/difftests/bin/Cargo.toml
tests/difftests/tests/Cargo.lock

This reverts commit b6172ae26476bdb7443de9b68069a61e62b24663.
The `cargo update` broke something that didn't break locally

Revert "Update `tracing-subscriber` for RUSTSEC-2025-0055"

---

crates/spirv-std/src/arch.rs
crates/spirv-std/src/float.rs
crates/spirv-std/src/ray_tracing.rs
tests/compiletests/ui/arch/read_clock_khr.rs

see https://github.com/Rust-GPU/rust-gpu/issues/393
> How are people feeling on replacing all the **trivial** `impl Vector<f32, 4>` with a plain `glam::Vec4`? 
> 
> pro:
> * clearer to read
> * functions returning `V: Vector` don't need any explicit declarations that it's a `Vec2`, in case of ambiguity:
https://github.com/Rust-GPU/rust-gpu/blob/fb42c2b1fe5454f7673163be9efe4bfe9e9807a2/crates/spirv-std/src/float.rs#L225
> 
> contra:
> * Both `Vec3` and `Vec3A` impl `Vector<f32, 3>`, so you can't use them interchangeably anymore. We expect most people to use `Vec3`, and conversion is a trivial `From::from`.
> 
> Cases where we are generic on the vector element type, or element count, or both should remain as generic, eg:
> https://github.com/Rust-GPU/rust-gpu/blob/fb42c2b1fe5454f7673163be9ef …

`glam`-infication of `spirv-std`

---

examples/runners/cpu/src/main.rs

It's supposed to produce a landscape with a small white sun, blue sky, and yellow ground. Instead it produces a small white sun and everything else is black. The problem is with the
`sun_intensity_extra_spec_const_factor` argument to `sky_shader::fs`.
- When running on the GPU, `sky_shader::fs` is called from `main_fs`, which has a spec_constant with a default value of 100.
- When running on the CPU, `sky_shader::fs` is called directly from the CPU shader's `main`, and it passes 1.
In other words, the CPU shader's sun intensity is 100x too small, which explains why it's so dark. This commit changes the value to 100, which makes the CPU shader produce the expected result.
(The shader later divides the intensity value by 100. There are comments about integration testing for specialization …

Fix the CPU sky-shader demo.

---

.github/workflows/ci.yaml

Updating the Vulkan SDK we used in CI came up in:
- https://github.com/Rust-GPU/rust-gpu/pull/379#discussion_r2335335011
Sadly, the [`NcStudios/VulkanCI@v1.2`](https://github.com/NcStudios/VulkanCI/tree/v1.2) action we were using to get SwiftShader on Windows, is stuck on an older version, and doesn't appear to be prompt to update in general.
So this PR replaces [`humbletim/install-vulkan-sdk@v1.2`](https://github.com/humbletim/install-vulkan-sdk/tree/v1.2) + [`NcStudios/VulkanCI@v1.2`](https://github.com/NcStudios/VulkanCI/tree/v1.2) with [`jakoch/install-vulkan-sdk-action@v1`](https://github.com/jakoch/install-vulkan-sdk-action/tree/v1), which supports SwiftShader (or Lavapipe, but I kept it on SwiftShader) for Windows (AFAICT that action downloads SwiftShader/Lavapipe releases from …

ci: switch to `jakoch/install-vulkan-sdk-action@v1` for Vulkan SDK + SwiftShader.

---

README.md
examples/README.md
examples/runners/ash/src/main.rs
examples/runners/wgpu/src/compute.rs
examples/shaders/compute-shader/src/lib.rs
examples/shaders/compute-shader/src/main.rs

Some improvements to the examples, mostly docs, a little code. Details in the individual commits.

Examples improvements

---

crates/spirv-builder/src/lib.rs
crates/spirv-builder/src/watch.rs
examples/runners/wgpu/src/lib.rs

This would be useful for Rust-GPU/cargo-gpu#112 to state via the Rust's type system that watch thread should never return by joining it.

Return `JoinHandle` of watching thread to the caller

---

examples/README.md
examples/runners/ash/src/main.rs

Just expanding the examples a little.

More shader/runner combos

---

examples/runners/ash/src/main.rs

The ash runner is over-engineered: it supports multiple pipelines, each one with a separate vertex/fragment shader pair, but it only ever uses one pipeline. The other runners don't support multiple pipelines, so this just seems like unnecessary complexity. This is bad because the examples are currently some of the best rust-gpu documentation there is.
More specifically:
- `rebuild_pipelines` is now just `rebuild_pipeline`, and `build_pipelines` is no longer needed.
- `compile_shaders` returns a pair instead of a `Vec`: one element for the vertex shader data, and one for the fragment shader data.
- RenderBase no longer needs `Vec` and `HashMap` elements, it can just store a single pipeline, a single vertex shader module, and a single fragment shader module.
- The following types are no …

Simplify the ash runner.
